music/urls.py
from django.conf.urls import url
from . import views

app_name = 'music'

urlpatterns = [
    # /music/
    url(r'^$', views.IndexView.as_view(), name='index'),
    # /music/<album_id>/
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'album/add/$', views.AlbumCreate.as_view(), name='album-add'),
]

website/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
        

music/models.py
from django.db import models
from django.core.urlresolvers import reverse

class Album(models.Model):
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    album_logo = models.CharField(max_length=1000)

    def get_absolute_url(self):
        return reverse('music:detail', kwargs={'pk':self.pk})

    def __str__(self):
        return self.album_title + ' - '+self.artist

class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=250)
    is_favorite = models.BooleanField(default=False)
    
    def __str__(self):
        return self.song_title

music/views.py
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Album, Song

class IndexView(generic.ListView):
    template_name = 'music/index.html'

    def get_queryset(self):
        return Album.objects.all()

class DetailView(generic.DetailView):
    model = Album
    template_name = 'music/detail.html'

class AlbumCreate(CreateView):
    model = Album
    fields = ['artist','album_title','genre','album_logo']

music/templates/music/album_form.html
{% extends 'music/base.html' %}
{% block title %}Add a New Album{% endblock %}
{% block albums_active  %}active{% endblock %}

{% block body %}
<div class="container-fluid">
	<div class="row">
		<div class="col-sm-12 col-md-7">
			<div class="panel panel-default">
				<div class="panel-body">
					<form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
						{% csrf_token %}
						{% include 'music/form-template.html' %}
						<div class="form-group">
							<div class="col-sm-offset-2 col-sm-10">
								<button type="submit" class="btn btn-success">Submit</button>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}

music/templates/music/base.html
<html>
<head>
	<title>{% block title %}Vibezz{% endblock %}</title>
	{% load staticfiles %}

	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
	<link rel="stylesheet" href="//fonts.googleapis.com/css?family=Open+Sans:300,400,600,700&amp;lang=en" />
	<link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}" />

</head>
<body>

<nav class="navbar navbar-inverse">
    <div class="container-fluid">
	<div class="navbar-header">
		<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
			 <span class="icon-bar"></span>
			 <span class="icon-bar"></span>
			 <span class="icon-bar"></span>
		</button>
		<a class="navbar-brand" href="{% url 'music:index' %}">Vibezz</a>
	</div>
	
    <!-- items -->
	<div class="collapse navbar-collapse" id="topNavBar">
		
		<ul class="nav navbar-nav">
			<li class="active">
				<a href="{% url 'music:index' %}">	
					<span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp;
					Albums
				</a>
			</li>
			<li class="">
				<a href="">	
					<span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp;
					Songs
				</a>
			</li>
		</ul>

		<form class="navbar-form navbar-left" role="search" method="get" action="#">
			<div class="form-group">
				<input type="text" class="form-control" name="q" value="">
			</div>
			<button type="submit" class="btn btn-default">Search</button>
		
		</form>

		<ul class="nav navbar-nav navbar-right">
			<li class="">
				<a href="{% url 'music:album-add' %}">	
					<span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;
					Add Album
				</a>
			</li>
			<li class="">
				<a href="#">	
					<span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;
					Logout
				</a>
			</li>
		</ul>

	</div>
    </div>
</nav>
{% block body %}
{% endblock %}

</body>
</html>

music/templates/music/detail.html
{% extends 'music/base.html' %}
{% block title %}Details page{% endblock %}
{% block body %}

<img src="{{album.album_logo}}" style="height:250px;width:300px;">

<h1>{{album.album_title}}</h1>
<h3>{{album.artist}}</h3>


	{% for song in album.song_set.all %}
		<label for="song{{ forloop.counter}}">
			{{song.song_title}}
			{% if song.is_favorite %}
				<img src="http://i.imgur.com/b9b13Rd.png" />
			{% endif %}
		</label><br>
	{% endfor %}

{% endblock %}

music/templates/music/form-template.html
{% for field in form %}
	<div class="form-group">
		<div class="col-sm-offset-2 col-sm-10">
			<span class="text-danger small">{{ field.errors }}</span>
		</div>
		<label class="control-label col-sm-2">{{ field.label_tag }}</label>
		<div class="col-sm-10">{{ field }}</div>
	</div>
{% endfor %}

music/templates/music/index.html
{% extends 'music/base.html' %}

{% block body %}
	{% if object_list %}
    	
    	<ul>
		<div class="row">
		    {% for album in object_list %}
			
						<div class="col-lg-4 col-md-4 col-sm-12 col-xs-12"><center>
							<div class="thumbnail" style="height:270px;width:300px;">
								<img src="{{album.album_logo}}" style="height:200px;width:280px;">
								<b><a href="{% url 'music:detail' album.id %}" style="text-decoration: none">{{album.album_title}}</a></b><br>
								<div class="row"><div class="col-md-4"></div> <div class="col-md-2"><div class="thumbnail" style="height:26px;width:30px;"><a href="#" style="text-decoration: none">	
									<center><span class="glyphicon glyphicon-star-empty" aria-hidden="true"></span></center>&nbsp;
									
								</a></div></div>
								<div class="col-md-1"><div class="thumbnail" style="height:26px;width:30px;"><a href="#" style="text-decoration: none">	
									<span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
									
								</a></div></div></div>
							</div>
						</center></div>
						
			
		    {% endfor %}
		</div>
    	</ul>
	{% else %}
   	         <h3>You don't have any albums</h3>
	{% endif %}
{% endblock %}